src/carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view
        )

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^update/$', cart_update, name='update'),
]

src/ebay_products/urls.py
from django.conf.urls import url

from .views import (
        EbayProductView,
        EbayProductDetailView,
        variation_api_view,
        )

urlpatterns = [
    url(r'^$', EbayProductView.as_view(), name='query'),
    url(r'^api/(?P<itemid>[\w-]+)/$', variation_api_view, name='api-variation'),
    url(r'^(?P<itemid>[\w-]+)/$', EbayProductDetailView.as_view(), name='detail'),

]

src/products_old/urls.py
from django.conf.urls import url

from .views import (
        ProductListView,
        # product_list_view,
        # ProductDetailView,
        # product_detail_view,
        # ProductFeaturedListView,
        # ProductFeaturedDetailView,
        ProductDetailSlugView
        )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),

]

src/shoppy/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
from django.conf.urls.i18n import i18n_patterns

from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView

# from products.views import (
#         ProductListView,
#         product_list_view,
#         ProductDetailView,
#         product_detail_view,
#         ProductFeaturedListView,
#         ProductFeaturedDetailView,
#         ProductDetailSlugView
#         )
from accounts.views import LoginView, RegisterView, GuestRegisterView
from addresses.views import (
    AddressCreateView,
    AddressListView,
    AddressUpdateView,
    checkout_address_create_view, 
    checkout_address_reuse_view
    )
from analytics.views import SalesView, SalesAjaxView
from billing.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view

from ebay_products.views import EbayCategoryProductView
from .views import home_page, about_page, contact_page, HomePageCategoryView

from .routers import router

urlpatterns = [
    url(r'^$', HomePageCategoryView.as_view(), name='home'),
    url(r'^about/$', about_page, name='about'),
    # url(r'^accounts/', RedirectView.as_view(url='/login')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include("accounts.urls", namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/$', AddressListView.as_view(), name='addresses'),
    url(r'^addresses/create/$', AddressCreateView.as_view(), name='address-create'),
    url(r'^addresses/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address-update'),
    url(r'^analytics/sales/$', SalesView.as_view(), name='sales-analytics'),
    url(r'^analytics/sales/data/$', SalesAjaxView.as_view(), name='sales-analytics-data'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^register/guest$', GuestRegisterView.as_view(), name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^orders/', include("orders.urls", namespace='orders')),
    url(r'^products_old/', include("products_old.urls", namespace='products_old')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^settings/$', RedirectView.as_view(url='/account')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^amazon_products/', include("amazon_products.urls", namespace='amazon_products')),
    url(r'^ebay_products/', include("ebay_products.urls", namespace='ebay_products')),
    # url(r'^featured/$', ProductFeaturedListView.as_view()),
    # url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
    # url(r'^products/$', ProductListView.as_view()),
    # url(r'^products-fbv/$', product_list_view),
    # #url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    # url(r'^products-fbv/(?P<pk>\d+)/$', product_detail_view),
    # url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    # url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include(router.urls)),
    url(r'^test_vue/$', TemplateView.as_view(template_name='ebay_products/api_test.html')),
    url(r'^test_abdulaziz/$', TemplateView.as_view(template_name='ebay_products/vue_abdulaziz_3.html')),
    url(r'^test_vuetify/$', TemplateView.as_view(template_name='ebay_products/vuetify_test.html'))
]

urlpatterns += i18n_patterns(
    #Django Admin
    url(r'^{}/'.format(settings.DJANGO_ADMIN_URL), admin.site.urls),
    )

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- Fontawesome CSS -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" /> -->

<!-- Google Fonts -->
<link href='https://fonts.googleapis.com/css?family=Ubuntu+Mono' rel='stylesheet' type='text/css'>

<link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">

<!-- <link rel="stylesheet" href="{% static "css/gallery.css" %}"> -->
<link rel="stylesheet" href="{% static 'css/fotorama.css' %}">

<!-- jquery-confirm css -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">

<!-- Custom Stripe Styling -->
<link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}">


<!-- Bootstrap-ecommerce stuff -->

<link rel="shortcut icon" type="image/x-icon" href='{% static "css/btsp_ecom/images/favicon.ico" %}'>

<!-- Bootstrap4 files-->
<script src="{% static 'js/btsp_ecom/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'css/btsp_ecom/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href='{% static "css/btsp_ecom/fonts/fontawesome/css/fontawesome-all.min.css" %}' type="text/css" rel="stylesheet">

<!-- plugin: owl carousel  -->
<link href='{% static "css/btsp_ecom/plugins/owlcarousel/assets/owl.carousel.min.css" %}' rel="stylesheet">
<link href='{% static "css/btsp_ecom/plugins/owlcarousel/assets/owl.theme.default.css" %}' rel="stylesheet">

<!-- custom style -->
<link href='{% static "css/btsp_ecom/css/ui.css" %}' rel="stylesheet" type="text/css"/>

<link href='{% static "css/btsp_ecom/css/responsive.css" %}' rel="stylesheet" media="only screen and (max-width: 1200px)"/>

<!-- Custom OWN shoppy style -->
<link href='{% static "css/main2.css" %}' rel="stylesheet" type="text/css"/>
<link href='{% static "css/dao.css" %}' rel="stylesheet" type="text/css"/>

src/templates/base/footer.html
{% load i18n %}


<!-- ========================= FOOTER ========================= -->
<footer class="section-footer bg-secondary">
  <div class="container">
    <section class="footer-top padding-top">
      <div class="row">
        <aside class="col-sm-3 col-md-3 white">
          <h5 class="title">Customer Services</h5>
          <ul class="list-unstyled">
            <li> <a href="#">Help center</a></li>
            <li> <a href="#">Money refund</a></li>
            <li> <a href="#">Terms and Policy</a></li>
            <li> <a href="#">Open dispute</a></li>
          </ul>
        </aside>
        <aside class="col-sm-3  col-md-3 white">
          <h5 class="title">My Account</h5>
          <ul class="list-unstyled">
            <li> <a href="#"> User Login </a></li>
            <li> <a href="#"> User register </a></li>
            <li> <a href="#"> Account Setting </a></li>
            <li> <a href="#"> My Orders </a></li>
            <li> <a href="#"> My Wishlist </a></li>
          </ul>
        </aside>
        <aside class="col-sm-3  col-md-3 white">
          <h5 class="title">About</h5>
          <ul class="list-unstyled">
            <li> <a href="#"> Our history </a></li>
            <li> <a href="#"> How to buy </a></li>
            <li> <a href="#"> Delivery and payment </a></li>
            <li> <a href="#"> Advertice </a></li>
            <li> <a href="#"> Partnership </a></li>
          </ul>
        </aside>
        <aside class="col-sm-3">
          <article class="white">
            <h5 class="title">Contacts</h5>
            <p>
              <strong>Phone: </strong> +123456789 <br> 
                <strong>Fax:</strong> +123456789
            </p>

             <div class="btn-group white">
                <a class="btn btn-facebook" title="Facebook" target="_blank" href="#"><i class="fab fa-facebook-f  fa-fw"></i></a>
                <a class="btn btn-instagram" title="Instagram" target="_blank" href="#"><i class="fab fa-instagram  fa-fw"></i></a>
                <a class="btn btn-youtube" title="Youtube" target="_blank" href="#"><i class="fab fa-youtube  fa-fw"></i></a>
                <a class="btn btn-twitter" title="Twitter" target="_blank" href="#"><i class="fab fa-twitter  fa-fw"></i></a>
            </div>
          </article>
        </aside>
      </div> <!-- row.// -->
      <br> 
    </section>
    <section class="footer-bottom row border-top-white">
      <div class="col-sm-6"> 
        <p class="text-white-50"></p>
      </div>
      <div class="col-sm-6">
        <p class="text-md-right text-white-50">
  Copyright &copy  <br>
<a href="/" class="text-white-50">Shoppy-ecommerce</a>
        </p>
      </div>
    </section> <!-- //footer-top -->
  </div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

src/templates/base/forms.html
{% extends "base.html" %}

{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method="POST" action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
  {% if next_url %}
  <input type='hidden' name='next' value='{{ next_url }}' />
  {% endif %}
{{ form.as_p }}
<button type="submit" class="btn btn-default">Save</button>
</form>
</div>

{% endblock %}

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products_old:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'cart:home' as cart_url %}
{% url 'register' as register_url %}
{% url 'account:home' as account_url %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}


{# Bootstrap-ecommerce templating #}

<header class="section-header my-header">


<section class="header-main shadow-sm">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="{{ home_url }}">
    {% if brand_name %} {{ brand_name }} {% else %} GoBazar {% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop" aria-controls="navbarTop" aria-expanded="false" aria-label="Toggle navigation" aria-haspopup="true" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTop">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == home_url %}active{% endif %}">
          <a href="{{ home_url }}" class="nav-link" >{% trans 'Home' %}</a>
        </li>
        <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
          <a href="{{ contact_url }}" class="nav-link" >{% trans 'Contact' %}</a>
        </li>
        <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
          <a href="{{ product_list_url }}" class="nav-link" >{% trans 'Products' %}</a>
        </li>
        <li class="nav-item dropdown"><a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sourcing</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Top  Suppliers</a></li>
                <li><a class="dropdown-item" href="#">Suppliers by Regions </a></li>
                <li><a class="dropdown-item" href="#">Online Retailer  </a></li>
            </ul>
        </li>
    <li class="nav-item dropdown">
      <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">   Services </a>
        <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Trade Assurance</a></li>
                  <li><a class="dropdown-item" href="#">Arabic</a></li>
                  <li><a class="dropdown-item" href="#">Logistics Service </a></li>
                  <li><a class="dropdown-item" href="#">Membership Services</a></li>
            </ul>
        </li>
    <li class="nav-item dropdown">
      <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="dropdownCommunity" aria-haspopup="true" aria-expanded="false">
        Community
      </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownCommunity">
              <li><a class="dropdown-item" href="#">Help Center</a></li>
              <li><a class="dropdown-item" href="#">Submit a Dispute </a></li>
              <li><a class="dropdown-item" href="#">For Suppliers </a></li>
            </ul>
        </li>

      </ul>



      <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
           <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% trans 'Account' %}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item {% if request.path == account_url %}active{% endif %}" href="{{ account_url }}">{% trans 'Home' %}</a>
              <a class="dropdown-item" href="#">{% trans 'Another action' %}</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ logout_url }}">{% trans 'Logout' %}</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item {% if request.path == register_url %}active{% endif %}">
            <a class="nav-link btn btn-default" href="{{ register_url }}">{% trans 'Register' %}</a>
          </li>
          <li class="nav-item {% if request.path == login_url %}active{% endif %}">
            <a class="nav-link btn btn-default" href="{{ login_url }}">{% trans 'Login' %}</a>
          </li>
          {% endif %}
       
          <li class="nav-item">
            <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
              <input name="next" type="hidden" value="{{ redirect_to }}">

                <ul class="languagepicker roundborders large">
                  {% get_current_language as LANGUAGE_CODE %}
                  {% get_available_languages as LANGUAGES %}
                  {% get_language_info_list for LANGUAGES as languages %}
                  <!-- {% for language in languages %}
                    <a href="#en" value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                      <li>
                        <img src="http://i64.tinypic.com/fd60km.png"/>
                          {{ language.name_local }} ({{ language.code }})
                      </li>
                    </a>
                  {% endfor %} -->
                </ul>
             </form>
          </li> 
  
      </ul>



    
    </div>
  </div>
</nav>
      <div class="row-sm justify-content-between align-items-center">
        <div class="col-lg-3-24 col-sm-3">
          <div class="category-wrap dropdown py-1">
            <a href="#" class="btn btn-light dropdown" data-toggle="dropdown" id="dropdownCategories">
              <i class="fa fa-bars"></i> Categories</a>
            <div class="dropdown-menu">
              <div class="row">
                <div class="col d-flex flex-direction-row align-items-center">
                   <div class="card">
                        <div class="card-body">
                          <a class="dropdown-item" href="#">Machinery  </a>
                          <a class="dropdown-item" href="#">Consumer Elec</a>
                          <a class="dropdown-item" href="#">Auto / Transportation</a>
                          <a class="dropdown-item" href="#">Appar </a>
                          <a class="dropdown-item" href="#">Home & Gard </a>
                          <a class="dropdown-item" href="#">Beaut </a> 
                        </div>
                        <div class="card-footer">
                            <span>
                              <a href="#">All Categories</a>
                            </span>
                        </div>
                      </div>
                      <div class="card">
                        <div class="card-body">
                          <a class="dropdown-item" href="#">Machinery  </a>
                          <a class="dropdown-item" href="#">Consumer Elec</a>
                          <a class="dropdown-item" href="#">Auto / Transportation</a>
                          <a class="dropdown-item" href="#">Appar </a>
                          <a class="dropdown-item" href="#">Home & Gard </a>
                          <a class="dropdown-item" href="#">Beaut </a> 
                        </div>
                        <div class="card-footer">
                            <span>
                              <a href="#">|</a>
                            </span>
                        </div>
                      </div>
                      <div class="card">
                        <div class="card-body">
                          <a class="dropdown-item" href="#">Machinery  </a>
                          <a class="dropdown-item" href="#">Consumer Elec</a>
                          <a class="dropdown-item" href="#">Auto / Transportation</a>
                          <a class="dropdown-item" href="#">Appar </a>
                          <a class="dropdown-item" href="#">Home & Gard </a>
                          <a class="dropdown-item" href="#">Beaut </a> 
                        </div>
                        <div class="card-footer">
                            <span>
                              <a href="#">All Categories</a>
                            </span>
                        </div>
                      </div>
                </div>

              </div>
            </div>
          </div> 
        </div>
        <div class="col-lg-14-24 col-sm-8">
        <form method="GET" action='{% url "ebay_products:query" %}' class="py-1">
              <div class="input-group w-100">
                
                  <input type="text" name='q' class="form-control" style="width:60%;" placeholder="Search" value='{{ request.GET.q }}'>
                  <select class="custom-select" name="category_name" style="overflow-y: auto">
                      <option value="">All type</option>
                      <option value="">Special</option>
                      <option value="">Only best</option>
                      <option value="">Latest</option>
                   </select>
                  <div class="input-group-append">
                    <button class="btn btn-warning" type="submit">
                      <i class="fa fa-search"></i> Search 
                    </button>
                  </div>
                </div>
            </form>
        </div> 
        <div class="col-lg-7-24 col-sm-12">
          <div class="widgets-wrap float-right row no-gutters py-1"
              style="align-items: center;justify-content: center;display: flex;">
            <div class="col-auto">
              <a href="{{ cart_url }}" class="widget-header">
                <div class="icontext">
                  <div class="icon-wrap">
                      <span class='navbar-cart-count'>{{request.session.cart_items}}</span><i class="text-warning icon-sm fa fa-shopping-cart"></i>
                  </div>
                </div>
              </a>
            </div>
            <!-- <div class="col-auto">
              <a href="#" class="widget-header">
                <div class="icontext">
                  <div class="icon-wrap">
                      <i class="text-warning icon-sm  fa fa-heart"></i>
                  </div>
                  <div class="text-wrap text-dark">
                    <span class="small round badge badge-secondary">0</span>
                    <div>Favorites</div>
                  </div>
                </div>
              </a>
            </div> -->
          </div>
        </div>
      </div>
  </div>
</section> 
</header> 

src/templates/base/old_navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products_old:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'cart:home' as cart_url %}
{% url 'register' as register_url %}
{% url 'account:home' as account_url %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}





<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ home_url }}">
      <img src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">
      {% if brand_name %} {{ brand_name }} {% else %} Turna eCommerce {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == home_url %}active{% endif %}">
          <a class="nav-link" href="{{ home_url }}">{% trans 'Home' %}<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
          <a class="nav-link" href="{{ contact_url }}">{% trans 'Contact' %}</a>
        </li>
        <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
          <a class="nav-link" href="{{ product_list_url }}">{% trans 'Products' %}</a>
        </li>
        {% if request.user.is_authenticated %}
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% trans 'Account' %}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item {% if request.path == account_url %}active{% endif %}" href="{{ account_url }}">{% trans 'Home' %}</a>
            <a class="dropdown-item" href="#">{% trans 'Another action' %}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ logout_url }}">{% trans 'Logout' %}</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item {% if request.path == register_url %}active{% endif %}">
          <a class="nav-link" href="{{ register_url }}">{% trans 'Register' %}</a>
        </li>
        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
          <a class="nav-link" href="{{ login_url }}">{% trans 'Login' %}</a>
        </li>
        {% endif %}
        <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
          <a class="nav-link" href="{{ cart_url }}"><span class='navbar-cart-count'>{{request.session.cart_items}}</span><i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
        </li>
        <li class="nav-item">

        <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}">
            <select name="language">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                        {{ language.name_local }} ({{ language.code }})
                    </option>
                {% endfor %}
            </select>
            <input type="submit" value="Go">
        </form>
        </li>
        <li>{{LANGUAGE_CODE}}
        </li>
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown link
          </a>
          <div class="dropdown-menu drop-menu-left" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> -->
      </ul>
      {% include 'search/snippets/search-form.html'%}
    </div>
  </div>
</nav>