src/accounts/passwords/urls.py
# accounts.passwords.urls.py 
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns  = [
        url(r'^password/change/$', 
                auth_views.PasswordChangeView.as_view(), 
                name='password_change'),
        url(r'^password/change/done/$',
                auth_views.PasswordChangeDoneView.as_view(), 
                name='password_change_done'),
        url(r'^password/reset/$', 
                auth_views.PasswordResetView.as_view(), 
                name='password_reset'),
        url(r'^password/reset/done/$', 
                auth_views.PasswordResetDoneView.as_view(), 
                name='password_reset_done'),
        url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
                auth_views.PasswordResetConfirmView.as_view(), 
                name='password_reset_confirm'),
        url(r'^password/reset/complete/$', 
                auth_views.PasswordResetCompleteView.as_view(), 
                name='password_reset_complete'),
]

src/accounts/urls.py
from django.conf.urls import url
from products_old.views import UserProductHistoryView
from .views import (
        AccountHomeView,
        AccountEmailActivateView,
        UserDetailUpdateView
        )

urlpatterns = [
    url(r'^$', AccountHomeView.as_view(), name='home'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'history/products_old/$', UserProductHistoryView.as_view(), name='user-product-history'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
	url(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name='resend-activation'),
]

src/carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view
        )

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^update/$', cart_update, name='update'),
]

src/products_old/urls.py
from django.conf.urls import url

from .views import (
        ProductListView,
        # product_list_view,
        # ProductDetailView,
        # product_detail_view,
        # ProductFeaturedListView,
        # ProductFeaturedDetailView,
        ProductDetailSlugView
        )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),

]

src/shoppy/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
from django.conf.urls.i18n import i18n_patterns

from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView

# from products.views import (
#         ProductListView,
#         product_list_view,
#         ProductDetailView,
#         product_detail_view,
#         ProductFeaturedListView,
#         ProductFeaturedDetailView,
#         ProductDetailSlugView
#         )
from accounts.views import LoginView, RegisterView, GuestRegisterView
from addresses.views import (
    AddressCreateView,
    AddressListView,
    AddressUpdateView,
    checkout_address_create_view, 
    checkout_address_reuse_view
    )
from analytics.views import SalesView, SalesAjaxView
from billing.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view

from ebay_products.views import EbayCategoryProductView
from .views import home_page, about_page, contact_page, HomePageCategoryView

from .routers import router

urlpatterns = [
    url(r'^$', HomePageCategoryView.as_view(), name='home'),
    url(r'^about/$', about_page, name='about'),
    # url(r'^accounts/', RedirectView.as_view(url='/login')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include("accounts.urls", namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/$', AddressListView.as_view(), name='addresses'),
    url(r'^addresses/create/$', AddressCreateView.as_view(), name='address-create'),
    url(r'^addresses/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address-update'),
    url(r'^analytics/sales/$', SalesView.as_view(), name='sales-analytics'),
    url(r'^analytics/sales/data/$', SalesAjaxView.as_view(), name='sales-analytics-data'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^register/guest$', GuestRegisterView.as_view(), name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^orders/', include("orders.urls", namespace='orders')),
    url(r'^products_old/', include("products_old.urls", namespace='products_old')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^settings/$', RedirectView.as_view(url='/account')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^amazon_products/', include("amazon_products.urls", namespace='amazon_products')),
    url(r'^ebay_products/', include("ebay_products.urls", namespace='ebay_products')),
    # url(r'^featured/$', ProductFeaturedListView.as_view()),
    # url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
    # url(r'^products/$', ProductListView.as_view()),
    # url(r'^products-fbv/$', product_list_view),
    # #url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    # url(r'^products-fbv/(?P<pk>\d+)/$', product_detail_view),
    # url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    # url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include(router.urls)),
    url(r'^test_vue/$', TemplateView.as_view(template_name='ebay_products/api_test.html')),
    url(r'^test_abdulaziz/$', TemplateView.as_view(template_name='ebay_products/vue_abdulaziz_3.html')),
    url(r'^test_vuetify/$', TemplateView.as_view(template_name='ebay_products/vuetify_test.html'))
]

urlpatterns += i18n_patterns(
    #Django Admin
    url(r'^{}/'.format(settings.DJANGO_ADMIN_URL), admin.site.urls),
    )

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, FormView, DetailView, View, UpdateView
from django.views.generic.edit import FormMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe

from shoppy.mixins import NextUrlMixin, RequestFormAttachMixin
from .forms import LoginForm, RegisterForm, GuestForm, ReactivateEmailForm, UserDetailChangeForm
from .models import GuestEmail, EmailActivation
from .signals import user_logged_in


# @login_required # /accounts/login/?next=some/path/
# def account_home_view(request):
#     return render(request, "accounts/home.html", {})

# LoginRequiredMixin
class AccountHomeView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/home.html'
    def get_object(self):
        return self.request.user

class AccountEmailActivateView(FormMixin, View):
    success_url = '/login/'
    form_class = ReactivateEmailForm
    key = None
    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, "Your email has been confirmed. Please login.")
                return redirect("login")
            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse("password_reset")
                    msg = """Your email has already been confirmed
                    Do you need to <a href="{link}">reset your password</a>?
                    """.format(link=reset_link)
                    messages.success(request, mark_safe(msg))
                    return redirect("login") 
        context = {'form': self.get_form(),'key': key}
        return render(request, 'registration/activation-error.html', context)

    def post(self, request, *args, **kwargs):
        # create form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = """Activation link sent, please check your email."""
        request = self.request
        messages.success(request, msg)
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user 
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        context = {'form': form, "key": self.key }
        return render(self.request, 'registration/activation-error.html', context)

class GuestRegisterView(NextUrlMixin,  RequestFormAttachMixin, CreateView):
    form_class = GuestForm
    default_next = '/register/'

    def get_success_url(self):
        return self.get_next_url()

    def form_invalid(self, form):
        return redirect(self.default_next)

class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/login.html'
    default_next = '/'

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)

class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/login/'

class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'accounts/detail-update-view.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Change Your Account Details'
        return context

    def get_success_url(self):
        return reverse("account:home")

# def guest_register_view(request):
#     form = GuestForm(request.POST or None)
#     context = {
#         "form": form
#     }
#     next_ = request.GET.get('next')
#     next_post = request.POST.get('next')
#     redirect_path = next_ or next_post or None
#     if form.is_valid():
#         email = form.cleaned_data.get("email")
#         new_guest_email = GuestEmail.objects.create(email=email)
#         request.session['guest_email_id'] = new_guest_email.id
#         if is_safe_url(redirect_path, request.get_host()):
#             return redirect(redirect_path)
#         else:
#             return redirect("/register/")
#     return redirect("/register/")

# def login_page(request):
#     form = LoginForm(request.POST or None)
#     context = {
#         "form": form
#     }
#     next_ = request.GET.get('next')
#     next_post = request.POST.get('next')
#     redirect_path = next_ or next_post or None
#     if form.is_valid():
#         username = form.cleaned_data.get("username")
#         password = form.cleaned_data.get("password")
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             try:
#                 del request.session['guest_email_id']
#             except:
#                 pass
#             if is_safe_url(redirect_path, request.get_host()):
#                 return redirect(redirect_path)
#             else:
#                 return redirect("/")
#         else:
#             # Return an 'invalid login' error message.
#             print("Error")
#     return render(request, "accounts/login.html", context)

# User = get_user_model()
# def register_page(request):
#     form = RegisterForm(request.POST or None)
#     context = {
#         "form": form
#     }
#     if form.is_valid():
#         form.save()
#         # print(form.cleaned_data)
#         # username = form.cleaned_data.get("username")
#         # email = form.cleaned_data.get("email")
#         # password = form.cleaned_data.get("password")
#         # new_user = User.objects.create_user(username, email, password)
#         # print(new_user)
#     return render(request, "accounts/register.html", context)

src/accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <label for='email'>Email</label>
  <input type='text' id='email' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" /><span class='help-text'>Cannot change email</span><br/>
  <button type='submit' class='btn btn-default my-3'>Save</button>
  <a href='{% url "password_change" %}'>Change Password</a>
</form>
</div>
{% endblock %}

src/accounts/templates/accounts/home.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
<div class='col-12'>
<h1>Account</h1>
<hr/>
</div>
<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Support</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "about" %}'>About</a>
                <a class='list-group-item' href='{% url "contact" %}'>Contact</a>
            </div>
      </div>
    </div>
</div>



<div class='col-12 col-md-3 my-3' id='billing'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Billing</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "orders:list" %}'>Orders</a>
                <a class='list-group-item' href='{% url "billing-payment-method" %}'>Payment Methods</a>
                <a class='list-group-item' href='{% url "addresses" %}'>Addresses</a>
                
                
            </div>
      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Account Details</h4> 
            <div class='list-group'>
                <a class='list-group-item' href='{% url "account:user-update" %}'>Update Details</a>
                <a class='list-group-item' href='{% url "password_change" %}'>Change Password</a>
                
            </div>

      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Preferences</h4> 
            <div class='list-group'>
                <a class='list-group-item' href='{% url "marketing-pref" %}'>Email Marketing</a>
                
            </div>

      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">History</h4> 
              <div class='list-group'>
                <a class='list-group-item' href='{% url "account:user-product-history" %}'>Products</a>
            </div>
      </div>
    </div>
</div>


</div>


{% endblock %}

src/accounts/templates/accounts/login.html
{% extends "base.html" %}


{% block content %}

{% load widget_tweaks %}
{% url 'register' as register_url %}

<div class="row" style="margin-top: 5em; margin-bottom: 5em;">
  <div class="col-md-4"></div>
	<div class="col-md-4">
		<div class="card">
		<article class="card-body">
			<h4 class="card-title text-center mb-4 mt-1">Sign in</h4>
			<hr>
			<form method="POST"> {% csrf_token %}
				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}
				 
				{% if form.errors %}
				<div class="alert alert-danger" role="alert"> 
					<ul class="errorlist">
						{% for field, errors in form.errors.items %}
							{% for error in errors %}
								<li>{{ error }}</li>
							{% endfor %}
						{% endfor %}
					</ul>
				</div>
				{% endif %}

				{% for field in form.visible_fields %}
				<div class="form-group">
					<div class="input-group">
					<div class="input-group-prepend">
						<span class="input-group-text"> <i class="fa {% if field.label == 'Email' %} fa-user {% else %} fa-lock {% endif %} "></i></span>
					</div>
						{% render_field field class="form-control" placeholder=field.label type=field.label %}
					</div>
				</div>
				{% endfor %}

				<div class="form-group">
						<button type="submit" class="btn btn-warning btn-block">Login</button>
				</div>
				<div class="form-group">
					<p class="text-center"><a href="#" class="btn btn-default">Forgot password?</a></p>
				</div>
				<div class="form-group">
						<div class="hr-sect">New to GoBazar?</div>
						<a type="submit" href="{{ register_url }}" class="btn btn-light btn-block">Create your GoBazar account</a>
				</div>
			</form>
		</article>
		</div>
	</div>
</div>

{% endblock %}

src/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}

{% load widget_tweaks %}

<div class="row" style="margin-top: 5em; margin-bottom: 5em;">
  <div class="col-md-4"></div>
	<div class="col-md-4">
		<div class="card">
		<article class="card-body">
			<h4 class="card-title text-center mb-4 mt-1">Registration</h4>
			<hr>
			<form method="POST">{% csrf_token %}
				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}
				 
				{% if form.errors %}
				<div class="alert alert-danger" role="alert"> 
					<ul class="errorlist">
						{% for field, errors in form.errors.items %}
							{% for error in errors %}
								<li>{{ error }}</li>
							{% endfor %}
						{% endfor %}
					</ul>
				</div>
				{% endif %}

				{% for field in form.visible_fields %}
				<div class="form-group">
					<div class="input-group">
					<div class="input-group-prepend">
							<!-- <label for="{{ field.id_for_label }}">{{ field.label }}</label> -->
						<span class="input-group-text"> <i class="fa {% if field.label == 'Full name' or field.label == 'Email' %} fa-user {% else %} fa-lock {% endif %} "></i></span>
					</div>
					{% if 'name' in field.label %}
						{% render_field field class="form-control" placeholder=field.label type='text' %}
					{% elif 'Email' in field.label %}
						{% render_field field class="form-control" placeholder=field.label type='email' %}
					{% elif 'Password' in field.label%}
						{% render_field field class="form-control" placeholder=field.label type='password' %}
					{% else %}
					    {% render_field field class="form-control" placeholder=field.label type='text' %}
					{% endif %}
					</div>
				</div>
				{% endfor %}



			<!-- <div class="form-group">
				<div class="input-group">
					<div class="input-group-prepend">
						<span class="input-group-text"> <i class="fa fa-user"></i> </span>
					</div>
					<input name="" class="form-control" placeholder="Full name" type="email">
				</div>
			</div>
			<div class="form-group">
				<div class="input-group">
					<div class="input-group-prepend">
						<span class="input-group-text"> <i class="fa fa-lock"></i> </span>
					</div>
					<input class="form-control" placeholder="******" type="password">
				</div>
			</div>
			<div class="form-group">
				<div class="input-group">
					<div class="input-group-prepend">
						<span class="input-group-text"> <i class="fa fa-lock"></i> </span>
					</div>
					<input class="form-control" placeholder="Password Confirmation" type="password">
				</div>
			</div> -->
			<div class="form-group">
				<button type="submit" class="btn btn-warning btn-block">Sign up</button>
			</div>
			</form>
		</article>
		</div>
	</div>
</div>
{% endblock %}