src/carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view
        )

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^update/$', cart_update, name='update'),
]

src/addresses/models.py
from django.db import models
from django.core.urlresolvers import reverse
from billing.models import BillingProfile

ADDRESS_TYPES = (
    ('billing', 'Billing'),
    ('shipping', 'Shipping')
)

class Address(models.Model):
    billing_profile = models.ForeignKey(BillingProfile)
    name            = models.CharField(max_length=120, null=True, blank=True, help_text='Shipping to? Who is it for?')
    nickname        = models.CharField(max_length=120, null=True, blank=True, help_text='Internal Reference Nickname')
    address_type    = models.CharField(max_length=120, choices=ADDRESS_TYPES)
    address_line_1  = models.CharField(max_length=120)
    address_line_2  = models.CharField(max_length=120, null=True, blank=True)
    city            = models.CharField(max_length=120)
    country         = models.CharField(max_length=120, default='Uzbekistan')
    state           = models.CharField(max_length=120)
    postal_code     = models.CharField(max_length=120)
    
    def __str__(self):
        if self.nickname:
            return str(self.nickname)
        return str(self.address_line_1)

    def get_absolute_url(self):
        return reverse("address-update", kwargs={"pk": self.pk})

    def get_short_address(self):
        for_name = self.name 
        if self.nickname:
            for_name = "{} | {},".format( self.nickname, for_name)
        return "{for_name} {line1}, {city}".format(
                for_name = for_name or "",
                line1 = self.address_line_1,
                city = self.city
            ) 

    def get_address(self):
        return "{for_name}\n{line1}\n{line2}\n{city}\n{state}, {postal}\n{country}".format(
                for_name = self.name or "",
                line1 = self.address_line_1,
                line2 = self.address_line_2 or "",
                city = self.city,
                state = self.state,
                postal= self.postal_code,
                country = self.country
            )

src/addresses/forms.py
from django import forms
from .models import Address

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            'nickname',
            'name',        
            #'billing_profile',
            #'address_type',
            'address_line_1',
            'address_line_2',
            'city',
            'country',
            'state',
            'postal_code',
        ]

class AddressCheckoutForm(forms.ModelForm):
    """
    User-related checkout address create form
    """
    class Meta:
        model = Address
        fields = [
            'nickname',
            'name',
            #'billing_profile',
            #'address_type',
            'address_line_1',
            'address_line_2',
            'city',
            'country',
            'state',
            'postal_code'
        ]

src/addresses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, UpdateView, CreateView
from django.shortcuts import render, redirect
from django.utils.http import is_safe_url

from billing.models import BillingProfile
from .forms import AddressCheckoutForm, AddressForm
from .models import Address

class AddressListView(LoginRequiredMixin, ListView):
    template_name = 'addresses/list.html'

    def get_queryset(self):
        request = self.request
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        return Address.objects.filter(billing_profile=billing_profile)



class AddressUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'addresses/update.html'
    form_class = AddressForm
    success_url = '/addresses'
    
    def get_queryset(self):
        request = self.request
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        return Address.objects.filter(billing_profile=billing_profile)


class AddressCreateView(LoginRequiredMixin, CreateView):
    template_name = 'addresses/update.html'
    form_class = AddressForm
    success_url = '/addresses'

    def form_valid(self, form):
        request = self.request
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        instance = form.save(commit=False)
        instance.billing_profile = billing_profile
        instance.save()
        return super(AddressCreateView, self).form_valid(form)

    # def get_queryset(self):
        
    #     return Address.objects.filter(billing_profile=billing_profile)


def checkout_address_create_view(request):
    form = AddressForm(request.POST or None)
    context = {
        "form": form
    }
    next_ = request.GET.get('next')
    next_post = request.POST.get('next')
    redirect_path = next_ or next_post or None
    if form.is_valid():
        print(request.POST)
        instance = form.save(commit=False)
        
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        
        if billing_profile is not None:
            address_type = request.POST.get('address_type', 'shipping')
            instance.billing_profile = billing_profile
            instance.address_type = address_type
            instance.save()
            
            request.session[address_type + "_address_id"] = instance.id
            print(address_type + "_address_id")
        else:
            print("Error here")
            return redirect("cart:checkout")
            
        if is_safe_url(redirect_path, request.get_host()):
            return redirect(redirect_path)
    return redirect("cart:checkout")
    
def checkout_address_reuse_view(request):
    if request.user.is_authenticated():
        context = {}
        next_ = request.GET.get('next')
        next_post = request.POST.get('next')
        redirect_path = next_ or next_post or None
        if request.method == "POST":
            print(request.POST)
            shipping_address = request.POST.get('shipping_address', None)
            address_type = request.POST.get('address_type', 'shipping')
            billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
            if shipping_address is not None:
                qs = Address.objects.filter(billing_profile=billing_profile, id=shipping_address)
                if qs.exists():
                    request.session[address_type + "_address_id"] = shipping_address
                if is_safe_url(redirect_path, request.get_host()):
                    return redirect(redirect_path)
    return redirect("cart:checkout")

src/addresses/templates/addresses/form.html
{% load widget_tweaks %}

	<form class="form-hotizontal" method="POST" action='{% if action_url %}{{ action_url }}{% else %}{% url "login" %}{% endif %}'> {% csrf_token %}
	  {% if next_url %}
	  <input type='hidden' name='next' value='{{ next_url }}' />
	  {% endif %}
	  
	  {% if address_type %}
	  <input type='hidden' name='address_type' value='{{ address_type }}'>
		{% endif %}
		
	{% for hidden in form.hidden_fields %}
		{{ hidden }}
	{% endfor %}
	
	{% for field in form.visible_fields %}
		<div class="form-group">
			<label for="{{ field.id_for_label }}">{{ field.label }}</label>
			{{ field|add_class:"form-control" }}
			{% for error in field.errors %}
				<span class="help-block">{{ error }}</span>
			{% endfor %}
		</div>
	{% endfor %}

    <!-- {{ form.as_p }} -->
    <button type="submit" class="btn btn-default">Submit</button>
  </form>

src/addresses/templates/addresses/list.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
<div class='col-12'>
<h1>Address{% if object_list.count > 1%}es{% endif %} <small><a href='{% url "address-create" %}'>Create New</a></small></h1>
<hr/>
</div>
</div>
<div class='row'>
        {% for obj in object_list %}
            <div class='col-12 col-md-3 my-3'>
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">{{ obj }}</h4> 
                     <small>{{ obj.get_address_type_display }}</small><br/>
                     <br/>
                     <h5>Address</h5>
                     {{ obj.get_address|linebreaks }}
                    
                    <a href='{{ obj.get_absolute_url }}' class='btn btn-default'>Edit</a>
                  </div>
                </div>
            </div>
        {% empty %}
         <p class='lead text-center'><a href='{% url "address-create" %}'>Create New</a></p>
        {% endfor %}
</div>
{% endblock %}

src/addresses/templates/addresses/prev_addresses.html
{% if address_qs.exists %}
	<form method='POST' action='{{ action_url }}'> {% csrf_token %}
  	  {% if next_url %}
  	  <input type='hidden' name='next' value='{{ next_url }}' />
  	  {% endif %}
	  
  	  {% if address_type %}
  	  <input type='hidden' name='address_type' value='{{ address_type }}'>
  	  {% endif %}
		
	{% for address in address_qs %}
		<label for='address-{{ address.id }}'>
			<input id='address-{{ address.id }}' type='radio' name='shipping_address' value='{{ address.id }}' />
		{{ address.address_line_1 }}
		</label></br>
	{% endfor %}
	<button type='submit' class='btn btn-success'>Use Address</button>
	</form>
{% endif %}

src/addresses/templates/addresses/update.html
{% extends "base.html" %}

{% block content %}

<div class='row'>
    <div class='col-10 mx-auto col-md-6 '>
        {% if form.instance.address_line_1  %}
        <h3 class='my-5'>Update Address</h3>
        {% else %}
        <h3 class='my-5'>Create Address</h3>
        {% endif %}
        <hr>
    <form method='POST' action=''> {% csrf_token %}
      {{ form.as_p }}
      <button type='submit' class='btn btn-default'>Save Address</button>
    </form>
    </div>

</div>

{% endblock %}